version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --no-include-email)
      - REPOSITORY_URI=641163449917.dkr.ecr.us-west-2.amazonaws.com/polydesk-www
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -f Dockerfile.buildenv -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
