version: 0.2

phases:
  build:
    commands:
      - npm install
      - ng build --prod
  post_build:
    commands:
      - aws s3 sync dist/polydesk-www s3://polydesk-www
      - aws s3 sync dist/polydesk-www s3://polydesk-www --delete
      - aws s3 sync dist/polydesk-www s3://www.polydesk.io
      - aws s3 sync dist/polydesk-www s3://www.polydesk.io --delete
