FROM node:8.12.0 as build
RUN apt-get update
RUN apt-get install zip unzip
RUN npm install -g @angular/cli@7.3.9
RUN apt-get update
RUN apt-get install zip unzip
RUN curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
RUN unzip awscliv2.zip
RUN ./aws/install
