FROM node:10.16.3 as build
RUN apt-get update
RUN apt-get --yes install zip unzip
RUN npm install -g @angular/cli@9.1.6
RUN curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
RUN unzip awscliv2.zip
RUN ./aws/install
